kernel/debug: panic_banner: print actual kernel version values
Prior to this change, `panic_banner` used to instead print:

    panicked at ./capsules/core/src/process_console.rs:1007:29:
    Process Console forced a kernel panic.
            Kernel version KERNEL_MAJOR_VERSION.KERNEL_MINOR_VERSION.KERNEL_PATCH_VERSION-KERNEL_PRERELEASE_VERSION

This is because `stringify!` only generates string representations of
the argument tokens, not their values.