chips/esp32-c3: fix interrupt in U-mode fault
It appears that the ESP32-C3 CPU has a bug or is non-compliant with the
RISC-V specification: when it gets an interrupt while in U-mode, the CPU
properly switches into M-mode, but will fault if it doesn't have
execute-permissions on the initial trap vector table (containing jumps
to Tock's single trap handler).

This change fixes that issue by providing user-mode execute-access to
the trap vector table, sacrificing two PMP entries for a new TOR region.
If we guaranteed alignment of `_start_trap_vectored`, we could reduce
that to one NAPOT region but it wouldn't buy us anything: we'd lose one
user MPU region either way.

Prior to this fix, running the `whileone` app pretty much immediately
faulted the CPU (panic output attached). Following the fix, the release
test suite passes.

Panic output for this bug:

    ---| Debug buffer not empty. Flushing. May repeat some of last message(s):
    Entering main loop.

    panicked at kernel/src/process_standard.rs:760:17:
    Process whileone had a fault
            Kernel version 2.4.0-dev1

    ---| RISC-V Machine State |---
    Last cause (mcause): Instruction access fault (interrupt=0, exception code=0x00000001)
    Last value (mtval):  0x40380154

    System register dump:
     mepc:    0x40385B40    mstatus:     0x00000081
     mtvec:   0x40380101
     mstatus: 0x00000081
      uie:    true   upie:   false
      sie:    false  spie:   false
      mie:    false  mpie:   true
      spp:    false
    ---| App Status |---
    𝐀𝐩𝐩: whileone   -   [Faulted]
     Events Queued: 0   Syscall Count: 3   Dropped Upcall Count: 0
     Restart Count: 0
     Last Syscall: Memop { operand: 11, arg0: 1070246316 }
     Completion Code: None

     ╔═══════════╤══════════════════════════════════════════╗
     ║  Address  │ Region Name    Used | Allocated (bytes)  ║
     ╚0x3FCAB608═╪══════════════════════════════════════════╝
                 │ Grant Ptrs       40
                 │ Upcalls         320
                 │ Process         744
      0x3FCAB1B8 ┼───────────────────────────────────────────
                 │ ▼ Grant           0
      0x3FCAB1B8 ┼───────────────────────────────────────────
                 │ Unused
      0x3FCAA9AC ┼───────────────────────────────────────────
                 │ ▲ Heap            0 |   2060               S
      0x3FCAA9AC ┼─────────────────────────────────────────── R
                 │ Data            428 |    428               A
      0x3FCAA800 ┼─────────────────────────────────────────── M
                 │ ▼ Stack          16 |   2048
      0x3FCAA7F0 ┼───────────────────────────────────────────
                 │ Unused
      0x3FCAA000 ┴───────────────────────────────────────────
                 .....
      0x403C8E14 ┬─────────────────────────────────────────── F
                 │ App Flash      3476                        L
      0x403C8080 ┼─────────────────────────────────────────── A
                 │ Protected       128                        S
      0x403C8000 ┴─────────────────────────────────────────── H

     R0 : 0x00000000    R16: 0x00000000
     R1 : 0x403C8158    R17: 0x00000000
     R2 : 0x3FCAA7F0    R18: 0x3FCAA000
     R3 : 0x00000000    R19: 0x00000000
     R4 : 0x00000000    R20: 0x00000000
     R5 : 0x3FCAA800    R21: 0x00000000
     R6 : 0x3FCAA9AC    R22: 0x00000000
     R7 : 0x0000003F    R23: 0x00000000
     R8 : 0x403C8080    R24: 0x00000000
     R9 : 0x3FCAA000    R25: 0x00000000
     R10: 0x00000000    R26: 0x00000000
     R11: 0x00000000    R27: 0x00000000
     R12: 0x00000000    R28: 0x00000000
     R13: 0x3FCAA000    R29: 0x00000000
     R14: 0x3FCAB000    R30: 0x00000000
     R15: 0x00045EEF    R31: 0x00000000
     PC : 0x40380154

     mcause: 0x00000001 (Instruction access fault)
     mtval:  0x40380154

     Total number of grant regions defined: 5
      Grant  0 : --          Grant  2 : --          Grant  4 : --
      Grant  1 : --          Grant  3 : --
     PMPUserMPUConfig {
      id: 2,
      is_dirty: false,
      app_memory_region: Some(1),
      regions:
         #00: start=0x403C8000, end=0x403C8E14, cfg=0x0D (TOR) (-r-x)
         #01: start=0x3FCAA000, end=0x3FCAA9AC, cfg=0x0B (TOR) (-rw-)
         #02: start=0x00000000, end=0x00000000, cfg=0x00 (OFF) (----)
         #03: start=0x00000000, end=0x00000000, cfg=0x00 (OFF) (----)
         #04: start=0x00000000, end=0x00000000, cfg=0x00 (OFF) (----)
         #05: start=0x00000000, end=0x00000000, cfg=0x00 (OFF) (----)
         #06: start=0x00000000, end=0x00000000, cfg=0x00 (OFF) (----)
         #07: start=0x00000000, end=0x00000000, cfg=0x00 (OFF) (----)
     }

    To debug libtock-c apps, run `make lst` in the app's
    folder and open the arch.0x403c8080.0x3fcaa000.lst file.