boards: debug: build lst seperately
This commit adds a make target for boards called `debug-lst` which
builds the debug version LST file.

It also disables LTO on debug builds since when it is set to true the
debug builds don't compile and throw this error:

```
make debug
   Compiling kernel v0.1.0 (file:///Users/bradjc/git/tock/kernel)
   Compiling imix v0.1.0 (file:///Users/bradjc/git/tock/boards/imix)
   Compiling cortexm4 v0.1.0 (file:///Users/bradjc/git/tock/arch/cortex-m4)
   Compiling capsules v0.1.0 (file:///Users/bradjc/git/tock/capsules)
   Compiling sam4l v0.1.0 (file:///Users/bradjc/git/tock/chips/sam4l)
error: can't perform LTO when compiling incrementally

error: Could not compile `imix`.

To learn more, run the command again with --verbose.
make: *** [target/thumbv7em-none-eabi/debug/imix] Error 101
```

Fixes #731