boards/redboard_artemis: Fixup Hard Fault exception
Fixup a hardfaul exception that is seen on every non-test boot of Tock.

This change ensures that the `svc` call in `apollo3::init()` is called
inline with `main()`. I'm not clear why, but if the `svc` is called
after a function call (a `push` op) we end up with a corrupted call
stack.

We need to call the `svc` op to ensure the FPU is correctly disabled (as
the boot loader enables it).

While we are chaning the inline let's also never inline `setup()` to
reduce the stack size usage (see
https://github.com/tock/tock/issues/2425).

Without this change, I see faults like this on the board:

panicked at 'Kernel HardFault.
        Kernel version release-2.1-rc1
        r0  0x10001ab8
        r1  0x10001da0
        r2  0x10000fe8
        r3  0x10001e08
        r12 0x10001acc
        lr  0x10001d70
        pc  0x0
        prs 0x0 [ N 0 Z 0 C 0 V 0 Q 0 GE 0000 ; ICI.IT 0 T false ; Exc 0-Thread Mode ]
        sp  0x10000f80
        top of stack     0x40008000
        bottom of stack  0x10000000
        SHCSR 0x0
        CFSR  0x20000
        HSFR  0x40000000
        Instruction Access Violation:       false
        Data Access Violation:              false
        Memory Management Unstacking Fault: false
        Memory Management Stacking Fault:   false
        Memory Management Lazy FP Fault:    false
        Instruction Bus Error:              false
        Precise Data Bus Error:             false
        Imprecise Data Bus Error:           false
        Bus Unstacking Fault:               false
        Bus Stacking Fault:                 false
        Bus Lazy FP Fault:                  false
        Undefined Instruction Usage Fault:  false
        Invalid State Usage Fault:          true
        Invalid PC Load Usage Fault:        false
        No Coprocessor Usage Fault:         false
        Unaligned Access Usage Fault:       false
        Divide By Zero:                     false
        Bus Fault on Vector Table Read:     false
        Forced Hard Fault:                  true
        Faulting Memory Address: (valid: false) 0xE000ED34
        Bus Fault Address:       (valid: false) 0xE000ED38
', arch/cortex-m/src/lib.rs:496:5
        Kernel version release-2.1-rc1

Fixes: e822de1742 "boards/redboard_artemis_nano: Setup initial tests"
Signed-off-by: Alistair Francis <alistair.francis@wdc.com>