host_emulation: fix zerocopy build dependence
Package zerocopy 0.3.1 introduced regression, using const generic
without #![feature(min_const_generics)].

This was found with rust nightly-2020-09-23-x86_64-unknown-linux-gnu.

When zerocopy dependency was introduced I was mislead by considering
equal sign as mathematical exact match equality, whereas it is caret
requirement, which means 0.3.x is allowed. See:

https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-cratesio

Log of the error:

error[E0658]: const generics are unstable
> .cargo/registry/src/github.com-1ecc6299db9ec823/zerocopy-0.3.1/src/lib.rs|71| 38
    |
71  |         unsafe impl<T: $trait, const N: usize> $trait for [T; N] {
    |                                      ^
...
263 | impl_for_composite_types!(FromBytes);
    | ------------------------------------- in this macro invocation

BUG=None
TEST=cargo build -p host_emulation

Signed-off-by: Krzysztof Kanas <kkanas@google.com>
Change-Id: I1a981c32e637b71eecfb69badce37910013037d2